name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
# Update 'Job name' and 'working_directory' as needed based on the module structure.
  stateful-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/stateful/'

  stateless-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/stateless-with-weekday-standby/'

# Seperate Job for TFlint workflow call
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@v2
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
